# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kredens < Formula
  desc "Simple CLI tool to manage environment credentials"
  homepage "https://github.com/arturtamborski/kredens"
  version "1.0.0"
  license "XD"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arturtamborski/kredens/releases/download/v1.0.0/kredens_Darwin_x86_64.zip"
      sha256 "1d63b41e29c94fc4aab8ccba292222cb0238d0875b6883c4830bd3e57bee186d"

      def install
        bin.install "kredens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arturtamborski/kredens/releases/download/v1.0.0/kredens_Darwin_arm64.zip"
      sha256 "40730c7d0555bf48e8d12c4336a954e389edc150f89501df3e3cc7f7ca5c32ce"

      def install
        bin.install "kredens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arturtamborski/kredens/releases/download/v1.0.0/kredens_Linux_x86_64.zip"
        sha256 "4adaf25fecf61f9a48a0be996d471bdf1daf14c1f498db6f61c57e0d8876abc1"

        def install
          bin.install "kredens"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arturtamborski/kredens/releases/download/v1.0.0/kredens_Linux_arm64.zip"
        sha256 "b0ce68b0373da60d850144f40e46a77483d2f463ea29f41830b0bc89deb5e7a6"

        def install
          bin.install "kredens"
        end
      end
    end
  end

  test do
    system "#{bin}/kredens", "help"
  end
end
