# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kredens < Formula
  desc "Simple CLI tool to manage environment credentials"
  homepage "https://github.com/arturtamborski/kredens"
  version "1.1.0"
  license "XD"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arturtamborski/kredens/releases/download/v1.1.0/kredens_Darwin_x86_64.zip"
      sha256 "7773beb805e8a97d59e41eaa2dc661bf6291cfbd41a0ee1525b23f55b1f9d0b2"

      def install
        bin.install "kredens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arturtamborski/kredens/releases/download/v1.1.0/kredens_Darwin_arm64.zip"
      sha256 "8e1b9d845b1c9c7d99206a3df8cc3441351435117a73d99c72cd07540d30d2d4"

      def install
        bin.install "kredens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arturtamborski/kredens/releases/download/v1.1.0/kredens_Linux_x86_64.zip"
        sha256 "d813ce44813af347bf88c99ad1ebb37e80a13b9d59a8607891a23fe0e87745b8"

        def install
          bin.install "kredens"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arturtamborski/kredens/releases/download/v1.1.0/kredens_Linux_arm64.zip"
        sha256 "ba1aa96b04f1142242855aebc46196e3c5c6e21e3dc75b7ed113bc03763455cc"

        def install
          bin.install "kredens"
        end
      end
    end
  end

  test do
    system "#{bin}/kredens", "help"
  end
end
