# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kredens < Formula
  desc "Simple CLI tool to manage environment credentials"
  homepage "https://github.com/arturtamborski/kredens"
  version "1.0.2"
  license "XD"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arturtamborski/kredens/releases/download/v1.0.2/kredens_Darwin_x86_64.zip"
      sha256 "06f4a7e427043f3f5473421b26d78c49a4729405c4043d3994b0a21b59031bf1"

      def install
        bin.install "kredens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arturtamborski/kredens/releases/download/v1.0.2/kredens_Darwin_arm64.zip"
      sha256 "f2fa67fba8dabe8066f9b4f69db85f8518e618505cfdd6d94d6b1082bc82c03e"

      def install
        bin.install "kredens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arturtamborski/kredens/releases/download/v1.0.2/kredens_Linux_x86_64.zip"
        sha256 "b69024d5091c6a7eb91565ab58536c136e91f8eec40914ac78105761cc501c87"

        def install
          bin.install "kredens"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arturtamborski/kredens/releases/download/v1.0.2/kredens_Linux_arm64.zip"
        sha256 "4fa5fc783061a726cb2d0fbb49a229c259f3d21f70fe27a06e4b69eea32fb75e"

        def install
          bin.install "kredens"
        end
      end
    end
  end

  test do
    system "#{bin}/kredens", "help"
  end
end
